// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzuJUmIDhIys2rUWhT5OPclx-Bpz0qbfg',
    appId: '1:349159251834:web:1c4a8ddac7f6b2381f00c3',
    messagingSenderId: '349159251834',
    projectId: 'maharto-cf57d',
    authDomain: 'maharto-cf57d.firebaseapp.com',
    storageBucket: 'maharto-cf57d.appspot.com',
    measurementId: 'G-CN3VSSY94N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiHuA6p2bgNbQImj8V_KiH2Krmh_3gRY',
    appId: '1:349159251834:android:ca8428b1c638e3a91f00c3',
    messagingSenderId: '349159251834',
    projectId: 'maharto-cf57d',
    storageBucket: 'maharto-cf57d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYGQvD5vieql1hVlfz5F6QRju-LichxE',
    appId: '1:349159251834:ios:ae2548db93bf87c71f00c3',
    messagingSenderId: '349159251834',
    projectId: 'maharto-cf57d',
    storageBucket: 'maharto-cf57d.appspot.com',
    iosClientId: '349159251834-co3h7ljfkndt0u8l4q1jsto16sprlf3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahaRto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYGQvD5vieql1hVlfz5F6QRju-LichxE',
    appId: '1:349159251834:ios:9d1b169741d66e711f00c3',
    messagingSenderId: '349159251834',
    projectId: 'maharto-cf57d',
    storageBucket: 'maharto-cf57d.appspot.com',
    iosClientId: '349159251834-qeqsr92tnsv5dmpk9jcq3iik68o7h4l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahaRto.RunnerTests',
  );
}
